# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Rule.create([
  { id: 1, name: "ナワバリ" },
  { id: 2, name: "ガチエリア" },
  { id: 3, name: "ガチホコ" },
  { id: 4, name: "ガチヤグラ" },
  { id: 5, name: "ガチアサリ" }
])

Map.create([
  { id: 0, name: "バッテラストリート" },
  { id: 1, name: "フジツボスポーツクラブ" },
  { id: 2, name: "ガンガゼ野外音楽堂" },
  { id: 3, name: "チョウザメ造船" },
  { id: 4, name: "海女美術大学" },
  { id: 5, name: "コンブトラック" },
  { id: 6, name: "マンタマリア号" },
  { id: 7, name: "ホッケふ頭" },
  { id: 8, name: "タチウオパーキング" },
  { id: 9, name: "エンガワ河川敷" },
  { id: 10, name: "モズク農園" },
  { id: 11, name: "Ｂバスパーク" },
  { id: 12, name: "デボン海洋博物館" },
  { id: 13, name: "ザトウマーケット" },
  { id: 14, name: "ハコフグ倉庫" },
  { id: 15, name: "アロワナモール" },
  { id: 16, name: "モンガラキャンプ場" },
  { id: 17, name: "ショッツル鉱山" },
  { id: 18, name: "アジフライスタジアム" },
  { id: 19, name: "ホテルニューオートロ" },
  { id: 20, name: "スメーシーワールド" },
  { id: 21, name: "アンチョビットゲームズ" },
  { id: 22, name: "ムツゴ楼" },
])

Weapon.create([
  { id: 1, name: "わかばシューター", order: 1, category: "わかばシューター" },
  { id: 2, name: "もみじシューター", order: 2, category: "わかばシューター" },
  { id: 3, name: "おちばシューター", order: 3, category: "わかばシューター" },
  { id: 4, name: "スプラシューター", order: 4, category: "スプラシューター" },
  { id: 5, name: "スプラシューターコラボ", order: 5, category: "スプラシューター" },
  { id: 6, name: "オクタシューター レプリカ", order: 6, category: "スプラシューター" },
  { id: 7, name: "スプラシューターベッチュー", order: 7, category: "プライムシューター" },
  { id: 8, name: "プライムシューター", order: 8, category: "プライムシューター" },
  { id: 9, name: "プライムシューターコラボ", order: 9, category: "プライムシューター" },
  { id: 10, name: "プライムシューターベッチュー", order: 10, category: "プライムシューター" },
  { id: 11, name: "シャープマーカー", order: 11, category: "シャープマーカー" },
  { id: 12, name: "シャープマーカーネオ", order: 12, category: "シャープマーカー" },
  { id: 13, name: "プロモデラーMG", order: 13, category: "プロモデラーMG" },
  { id: 14, name: "プロモデラーRG", order: 14, category: "プロモデラーMG" },
  { id: 15, name: "プロモデラーPG", order: 15, category: "プロモデラーMG" },
  { id: 16, name: "N-ZAP85", order: 16, category: "N-ZAP85" },
  { id: 17, name: "N-ZAP89", order: 17, category: "N-ZAP85" },
  { id: 18, name: "N-ZAP83", order: 18, category: "N-ZAP85" },
  { id: 19, name: ".52ガロン", order: 19, category: ".52ガロン" },
  { id: 20, name: ".52ガロンデコ", order: 20, category: ".52ガロン" },
  { id: 21, name: ".52ガロンベッチュー", order: 21, category: ".52ガロン" },
  { id: 22, name: ".96ガロン", order: 22, category: ".96ガロン" },
  { id: 23, name: ".96ガロンデコ", order: 23, category: ".96ガロン" },
  { id: 24, name: "ジェットスイーパー", order: 24, category: "ジェットスイーパー" },
  { id: 25, name: "ジェットスイーパーカスタム", order: 25, category: "ジェットスイーパー" },
  { id: 26, name: "L3リールガン", order: 26, category: "L3リールガン" },
  { id: 27, name: "L3リールガンD", order: 27, category: "L3リールガン" },
  { id: 28, name: "L3リールガンベッチュー", order: 28, category: "L3リールガン" },
  { id: 29, name: "H3リールガン", order: 29, category: "H3リールガン" },
  { id: 30, name: "H3リールガンD", order: 30, category: "H3リールガン" },
  { id: 31, name: "H3リールガンチェリー", order: 31, category: "H3リールガン" },
  { id: 32, name: "ボールドマーカー", order: 32, category: "ボールドマーカー" },
  { id: 33, name: "ボールドマーカーネオ", order: 33, category: "ボールドマーカー" },
  { id: 34, name: "ボールドマーカー7", order: 34, category: "ボールドマーカー" },
  { id: 35, name: "ボトルガイザー", order: 35, category: "ボトルガイザー" },
  { id: 36, name: "ボトルガイザーフォイル", order: 36, category: "ボトルガイザー" },
  { id: 37, name: "ホットブラスター", order: 37, category: "ホットブラスター" },
  { id: 38, name: "ホットブラスターカスタム", order: 38, category: "ホットブラスター" },
  { id: 39, name: "ラピッドブラスター", order: 39, category: "ラピッドブラスター" },
  { id: 40, name: "ラピッドブラスターデコ", order: 40, category: "ラピッドブラスター" },
  { id: 41, name: "ラピッドブラスターベッチュー", order: 41, category: "ラピッドブラスター" },
  { id: 42, name: "ノヴァブラスター", order: 42, category: "ノヴァブラスター" },
  { id: 43, name: "ノヴァブラスターネオ", order: 43, category: "ノヴァブラスター" },
  { id: 44, name: "ノヴァブラスターベッチュー", order: 44, category: "ノヴァブラスター" },
  { id: 45, name: "クラッシュブラスター", order: 45, category: "クラッシュブラスター" },
  { id: 46, name: "クラッシュブラスターネオ", order: 46, category: "クラッシュブラスター" },
  { id: 47, name: "Rブラスターエリート", order: 47, category: "Rブラスターエリート" },
  { id: 48, name: "Rブラスターエリートデコ", order: 48, category: "Rブラスターエリート" },
  { id: 49, name: "ロングブラスター", order: 49, category: "ロングブラスター" },
  { id: 50, name: "ロングブラスターカスタム", order: 50, category: "ロングブラスター" },
  { id: 51, name: "ロングブラスターネクロ", order: 51, category: "ロングブラスター" },
  { id: 52, name: "スプラローラー", order: 52, category: "スプラローラー" },
  { id: 53, name: "スプラローラーコラボ", order: 53, category: "スプラローラー" },
  { id: 54, name: "スプラローラーベッチュー", order: 54, category: "スプラローラー" },
  { id: 55, name: "ダイナモローラー", order: 55, category: "ダイナモローラー" },
  { id: 56, name: "ダイナモローラーテスラ", order: 56, category: "ダイナモローラー" },
  { id: 57, name: "ダイナモローラーベッチュー", order: 57, category: "ダイナモローラー" },
  { id: 58, name: "カーボンローラー", order: 58, category: "カーボンローラー" },
  { id: 59, name: "カーボンローラーデコ", order: 59, category: "カーボンローラー" },
  { id: 60, name: "ヴァリアブルローラー", order: 60, category: "ヴァリアブルローラー" },
  { id: 61, name: "ヴァリアブルローラーフォイル", order: 61, category: "ヴァリアブルローラー" },
  { id: 62, name: "ホクサイ", order: 62, category: "ホクサイ" },
  { id: 63, name: "ホクサイ・ヒュー", order: 63, category: "ホクサイ" },
  { id: 64, name: "ホクサイベッチュー", order: 64, category: "ホクサイ" },
  { id: 65, name: "パブロ", order: 65, category: "パブロ" },
  { id: 66, name: "パブロ・ヒュー", order: 66, category: "パブロ" },
  { id: 67, name: "パーマネント・パブロ", order: 67, category: "パブロ" },
  { id: 68, name: "スプラチャージャー", order: 68, category: "スプラチャージャー" },
  { id: 69, name: "スプラスコープ", order: 69, category: "スプラチャージャー" },
  { id: 70, name: "スプラチャージャーコラボ", order: 70, category: "スプラチャージャー" },
  { id: 71, name: "スプラスコープコラボ", order: 71, category: "スプラチャージャー" },
  { id: 72, name: "スプラチャージャーベッチュー", order: 72, category: "スプラチャージャー" },
  { id: 73, name: "スプラスコープベッチュー", order: 73, category: "スプラチャージャー" },
  { id: 74, name: "リッター4K", order: 74, category: "リッター4K" },
  { id: 75, name: "4Kスコープ", order: 75, category: "リッター4K" },
  { id: 76, name: "リッター4Kカスタム", order: 76, category: "リッター4K" },
  { id: 77, name: "4Kスコープカスタム", order: 77, category: "リッター4K" },
  { id: 78, name: "ソイチューバー", order: 78, category: "ソイチューバー" },
  { id: 79, name: "ソイチューバーカスタム", order: 79, category: "ソイチューバー" },
  { id: 80, name: "スクイックリンα", order: 80, category: "スクイックリンα" },
  { id: 81, name: "スクイックリンβ", order: 81, category: "スクイックリンα" },
  { id: 82, name: "スクイックリンγ", order: 82, category: "スクイックリンα" },
  { id: 83, name: "14式竹筒銃・甲", order: 83, category: "14式竹筒銃・甲" },
  { id: 84, name: "14式竹筒銃・乙", order: 84, category: "14式竹筒銃・甲" },
  { id: 85, name: "14式竹筒銃・丙", order: 85, category: "14式竹筒銃・甲" },
  { id: 86, name: "バケットスロッシャー", order: 86, category: "バケットスロッシャー" },
  { id: 87, name: "バケットスロッシャーデコ", order: 87, category: "バケットスロッシャー" },
  { id: 88, name: "バケットスロッシャーソーダ", order: 88, category: "バケットスロッシャー" },
  { id: 89, name: "ヒッセン", order: 89, category: "ヒッセン" },
  { id: 90, name: "ヒッセン・ヒュー", order: 90, category: "ヒッセン" },
  { id: 91, name: "スクリュースロッシャー", order: 91, category: "スクリュースロッシャー" },
  { id: 92, name: "スクリュースロッシャーネオ", order: 92, category: "スクリュースロッシャー" },
  { id: 93, name: "スクリュースロッシャーベッチュー", order: 93, category: "スクリュースロッシャー" },
  { id: 94, name: "エクスプロッシャー", order: 94, category: "エクスプロッシャー" },
  { id: 95, name: "エクスプロッシャーカスタム", order: 95, category: "エクスプロッシャー" },
  { id: 96, name: "オーバーフロッシャー", order: 96, category: "オーバーフロッシャー" },
  { id: 97, name: "オーバーフロッシャーデコ", order: 97, category: "オーバーフロッシャー" },
  { id: 98, name: "バレルスピナー", order: 98, category: "バレルスピナー" },
  { id: 99, name: "バレルスピナーデコ", order: 99, category: "バレルスピナー" },
  { id: 100, name: "バレルスピナーリミックス", order: 100, category: "バレルスピナー" },
  { id: 101, name: "スプラスピナー", order: 101, category: "スプラスピナー" },
  { id: 102, name: "スプラスピナーコラボ", order: 102, category: "スプラスピナー" },
  { id: 103, name: "スプラスピナーベッチュー", order: 103, category: "スプラスピナー" },
  { id: 104, name: "ハイドラント", order: 104, category: "ハイドラント" },
  { id: 105, name: "ハイドラントカスタム", order: 105, category: "ハイドラント" },
  { id: 106, name: "クーゲルシュライバー", order: 106, category: "クーゲルシュライバー" },
  { id: 107, name: "クーゲルシュライバー・ヒュー", order: 107, category: "クーゲルシュライバー" },
  { id: 108, name: "ノーチラス47", order: 108, category: "ノーチラス47" },
  { id: 109, name: "ノーチラス79", order: 109, category: "ノーチラス47" },
  { id: 110, name: "スプラマニューバー", order: 110, category: "スプラマニューバー" },
  { id: 111, name: "スプラマニューバーコラボ", order: 111, category: "スプラマニューバー" },
  { id: 112, name: "スプラマニューバーベッチュー", order: 112, category: "スプラマニューバー" },
  { id: 113, name: "スパッタリー", order: 113, category: "スパッタリー" },
  { id: 114, name: "スパッタリー・ヒュー", order: 114, category: "スパッタリー" },
  { id: 115, name: "スパッタリークリア", order: 115, category: "スパッタリー" },
  { id: 116, name: "デュアルスイーパー", order: 116, category: "デュアルスイーパー" },
  { id: 117, name: "デュアルスイーパーカスタム", order: 117, category: "デュアルスイーパー" },
  { id: 118, name: "ケルビン525", order: 118, category: "ケルビン525" },
  { id: 119, name: "ケルビン525デコ", order: 119, category: "ケルビン525" },
  { id: 120, name: "ケルビン525ベッチュー", order: 120, category: "ケルビン525" },
  { id: 121, name: "クアッドホッパーブラック", order: 121, category: "クアッドホッパーブラック" },
  { id: 122, name: "クアッドホッパーホワイト", order: 122, category: "クアッドホッパーブラック" },
  { id: 123, name: "パラシェルター", order: 123, category: "パラシェルター" },
  { id: 124, name: "パラシェルターソレーラ", order: 124, category: "パラシェルター" },
  { id: 125, name: "キャンピングシェルター", order: 125, category: "キャンピングシェルター" },
  { id: 126, name: "キャンピングシェルターソレーラ", order: 126, category: "キャンピングシェルター" },
  { id: 127, name: "キャンピングシェルターカーモ", order: 127, category: "キャンピングシェルター" },
  { id: 128, name: "スパイガジェット", order: 128, category: "スパイガジェット" },
  { id: 129, name: "スパイガジェットソレーラ", order: 129, category: "スパイガジェット" },
  { id: 130, name: "スパイガジェットベッチュー", order: 130, category: "スパイガジェット" },
])

User.create([
  { id: 1, name: "testaccount", password: "WnrU4FCq4nklrh", nickname: "test_account", favorite_weapon_id: 1, admnflg: true }
])
